theme: jekyll-theme-minimal
title: Foundations of Bioninformatics UCSD
description: Class Portfolio and Fumblings of an Introductory Student
logo: https://bioboot.github.io/bggn213_S18/assets/img/logo.png
